services:
  transip-firewall-ip-sync:
    build: .
    container_name: transip-firewall-ip-sync
    restart: unless-stopped

    environment:
      IP_CHECK_INTERVAL: ${IP_CHECK_INTERVAL:-30}
      TRANSIP_UPDATE_COOLDOWN: ${TRANSIP_UPDATE_COOLDOWN:-300}

      TRANSIP_ACCOUNT_NAME: ${TRANSIP_ACCOUNT_NAME}
      TRANSIP_VPS_NAME: ${TRANSIP_VPS_NAME}
      TRANSIP_PRIVATE_KEY_FILE: ${TRANSIP_PRIVATE_KEY_FILE:-/config/transip_private_key.pem}
      TRANSIP_FIREWALL_RULES: ${TRANSIP_FIREWALL_RULES}
      TRANSIP_UPDATE_DNS: ${TRANSIP_UPDATE_DNS}
      TRANSIP_DNS_RECORDS: ${TRANSIP_DNS_RECORDS}
      TRANSIP_DNS_TTL: ${TRANSIP_DNS_TTL}

    volumes:
      - ${TRANSIP_DATA_PATH:-./data}:/data
      - ${TRANSIP_CONFIG_PATH:-./config}:/config:ro