services:
  transip-firewall-ip-sync:
    build: .
    container_name: transip-firewall-ip-sync
    restart: unless-stopped

    environment:
      IP_CHECK_INTERVAL: ${IP_CHECK_INTERVAL:-30}
      TRANSIP_UPDATE_COOLDOWN: ${TRANSIP_UPDATE_COOLDOWN:-300}
      TRANSIP_ACCOUNT_NAME: ${TRANSIP_ACCOUNT_NAME}
      TRANSIP_PRIVATE_KEY: ${TRANSIP_PRIVATE_KEY}
      TRANSIP_VPS_NAME: ${TRANSIP_VPS_NAME}

    volumes:
      - ./data:/data